### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by arturmuller** [pavelvolek/redux-keen#5]
We really should add tests to this package.

**Comment by arturmuller** [comment]
Hey @pavelvolek, @saamo — what do you think of this: https://github.com/pavelvolek/redux-keen/blob/tests/test/test.js

**Comment by arturmuller** [comment]
Bump @pavelvolek, @saamo.

**Comment by pavelvolek** [comment]
I think it's fine, good job Art. Can we merge it into master?

**Comment by pavelvolek** [comment]
Having the tests merged into master, I am closing this issue.
