### ISSUE TITLE
Wrong code published to npm

### ISSUE THREAD

**Issue by markdalgleish** [pavelvolek/redux-keen#7]
When I pull down the latest code and run `npm run build`, the code in `lib/index.js` doesn't match what's been published to npm.

In particular, the following line is causing me issues, as I'm trying to avoid loading the full `keen-js` library:

``` js
var _keenJs = require('keen-js');
```

Did something go wrong in the publish step? Did you publish after temporarily messing with `src/index.js`?

**Comment by pavelvolek** [comment]
Hey, I didn't notice that those lines were left behind after the merge. It is fixed on master, so I just published the new version.

**Comment by markdalgleish** [comment]
Perfect. Thank you! :smiley:

**Comment by markdalgleish** [comment]
Sorry, you're right, I had a look at my pull request and I had failed to clean up the import statement. Sorry about that.

**Comment by pavelvolek** [comment]
No problem :)
